# Where things are
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes
collections:
  posts:
    output:   true

# Handling Reading
safe:                 true
include:              [".htaccess"]
exclude:              [
  "*/README.md",
  "Gemfile",
  "Gemfile.lock",
  "Makefile",
  "node_modules",
  "README.md",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/"
]
keep_files:           [".git", ".svn"]
encoding:             "utf-8"
markdown_ext:         "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach:  false
port:    5000
host:    127.0.0.1
#url:     ""
# baseurl: "/"
show_dir_listing: false

# Outputting
permalink:     /:year/:title/
timezone:      null

quiet:    false
verbose:  false
defaults:
  -
    values:
      layout: "default"

liquid:
  error_mode: warn

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

# Extensions
gems:
  - jekyll-redirect-from  # enable "refirect_from" in front matter

sass:
  style: compressed

copyright:
  year: 2017

# Cache busting.
#
# Change the cache tag to invalid site.css, site.js, and favicons.
cache_tag: 1
